sources:
  - name: main
    tables:
      - name: bike_data
        columns:
          - name: tripduration
            data_type: CHARACTER VARYING(256)
            description: "Trip Duration (seconds)"
          - name: starttime
            data_type: CHARACTER VARYING(256)
          - name: stoptime
            data_type: CHARACTER VARYING(256)
          - name: start station id
            data_type: CHARACTER VARYING(256)
          - name: start station name
            data_type: CHARACTER VARYING(256)
          - name: start station latitude
            data_type: CHARACTER VARYING(256)
          - name: start station longitude
            data_type: CHARACTER VARYING(256)
          - name: end station id
            data_type: CHARACTER VARYING(256)
          - name: end station name
            data_type: CHARACTER VARYING(256)
          - name: end station latitude
            data_type: CHARACTER VARYING(256)
          - name: end station longitude
            data_type: CHARACTER VARYING(256)
          - name: bikeid
            data_type: CHARACTER VARYING(256)
          - name: usertype
            data_type: CHARACTER VARYING(256)
            description: "User Type (Customer = 24-hour pass or 3-day pass user; Subscriber = Annual Member)"
          - name: birth year
            data_type: CHARACTER VARYING(256)
          - name: gender
            data_type: CHARACTER VARYING(256)
            description: "Gender (Zero=unknown; 1=male; 2=female)"
          - name: ride_id
            data_type: CHARACTER VARYING(256)
          - name: rideable_type
            data_type: CHARACTER VARYING(256)
          - name: started_at
            data_type: CHARACTER VARYING(256)
          - name: ended_at
            data_type: CHARACTER VARYING(256)
          - name: start_station_name
            data_type: CHARACTER VARYING(256)
          - name: start_station_id
            data_type: CHARACTER VARYING(256)
          - name: end_station_name
            data_type: CHARACTER VARYING(256)
          - name: end_station_id
            data_type: CHARACTER VARYING(256)
          - name: start_lat
            data_type: CHARACTER VARYING(256)
          - name: start_lng
            data_type: CHARACTER VARYING(256)
          - name: end_lat
            data_type: CHARACTER VARYING(256)
          - name: end_lng
            data_type: CHARACTER VARYING(256)
          - name: member_casual
            data_type: CHARACTER VARYING(256)
          - name: filename
            data_type: CHARACTER VARYING(256)

      - name: central_park_weather
        columns:
          - name: station
            data_type: CHARACTER VARYING(256)
            description: "Station ID"
            tests:
              - unique
              - dbt_expectations.expect_column_to_exist
              - not_null
          - name: name
            data_type: CHARACTER VARYING(256)
            description: "Station name, city, state"
          - name: date
            data_type: CHARACTER VARYING(256)
          - name: awnd
            data_type: CHARACTER VARYING(256)
            description: "Average wind speed"
          - name: prcp
            data_type: CHARACTER VARYING(256)
            description: "Precipitation"
          - name: snow
            data_type: CHARACTER VARYING(256)
          - name: snwd
            data_type: CHARACTER VARYING(256)
            description: "Snowfall depth"
          - name: tmax
            data_type: CHARACTER VARYING(256)
            description: "Maximum temperature"
          - name: tmin
            data_type: CHARACTER VARYING(256)
            description: "Minimum temperature"
          - name: filename
            data_type: CHARACTER VARYING(256)

      - name: fhv_bases
        columns:
          - name: base_number
            data_type: CHARACTER VARYING(256)
            description: "The TLC license number of the dispatching base"
            tests:
              - unique
              - dbt_expectations.expect_column_to_exist
              - not_null
          - name: base_name
            data_type: CHARACTER VARYING(256)
            description: "The official name of the base entity"
          - name: dba
            description: "The 'doing business as' name of the base"
            data_type: CHARACTER VARYING(256)
          - name: dba_category
            data_type: CHARACTER VARYING(256)
            description: "What company this business belongs to
                          • juno
                          • lyft
                          • other
                          • uber
                          • via "
          - name: filename
            data_type: CHARACTER VARYING(256)

      - name: fhv_tripdata
        columns:
          - name: dispatching_base_num
            desciption: "The TLC Base License Number of the base that dispatched the trip"
            data_type: CHARACTER VARYING(256)
            tests:
              - not_null
              - dbt_expectations.expect_column_to_exist
              - relationships:
                  to: source('main','fhv_bases')
                  field: base_number
                  config:
                    severity: warn
          - name: pickup_datetime
            data_type: TIMESTAMP
          - name: dropoff_datetime
            data_type: TIMESTAMP
          - name: pulocationid
            data_type: DOUBLE
          - name: dolocationid
            data_type: DOUBLE
          - name: sr_flag
            desciption: "Indicates if the trip was a part of a shared ride chain offered by a High Volume FHV company (e.g. Uber Pool, Lyft Line). 
                         • 1: shared trips
                         • null: non-shared rides"
            data_type: INTEGER
          - name: affiliated_base_number
            data_type: CHARACTER VARYING(256)
          - name: filename
            data_type: CHARACTER VARYING(256)

      - name: fhvhv_tripdata
        columns:
          - name: hvfhs_license_num
            data_type: CHARACTER VARYING(256)
            description: "The TLC license number of the HVFHS base or business
                          As of September 2019, the HVFHS licensees are the following:
                          • HV0002: Juno
                          • HV0003: Uber
                          • HV0004: Via
                          • HV0005: Lyft"
          - name: dispatching_base_num
            data_type: CHARACTER VARYING(256)
            description: "The TLC Base License Number of the base that dispatched the trip"
          - name: originating_base_num
            data_type: CHARACTER VARYING(256)
          - name: request_datetime
            data_type: TIMESTAMP
          - name: on_scene_datetime
            data_type: TIMESTAMP
            description: "date/time when driver arrived at the pick-up location (Accessible Vehicles-only)"
          - name: pickup_datetime
            data_type: TIMESTAMP
            tests:
              - not_null
              - dbt_expectations.expect_column_to_exist
          - name: dropoff_datetime
            data_type: TIMESTAMP
            tests:
              - not_null
              - dbt_expectations.expect_column_to_exist
          - name: pulocationid
            data_type: BIGINT
          - name: dolocationid
            data_type: BIGINT
          - name: trip_miles
            data_type: DOUBLE
            tests:
              - dbt_expectations.expect_column_values_to_be_between:
                  min_value: 0 
                  max_value: 30000 
                  config:
                    severity: warn
          - name: trip_time
            data_type: BIGINT
          - name: base_passenger_fare
            data_type: DOUBLE
          - name: tolls
            data_type: DOUBLE
          - name: bcf
            data_type: DOUBLE
            description: "total amount collected in trip for Black Car Fund"
          - name: sales_tax
            data_type: DOUBLE
          - name: congestion_surcharge
            data_type: DOUBLE
            description: "total amount collected in trip for NYS congestion surcharge"
          - name: airport_fee
            data_type: DOUBLE
          - name: tips
            data_type: DOUBLE
          - name: driver_pay
            data_type: DOUBLE
          - name: shared_request_flag
            data_type: CHARACTER VARYING(256)
            description: "Did the passenger agree to a shared/pooled ride, regardless of whether they were matched? (Y/N)"
            tests:
              - accepted_values:
                  values: ['Y', 'N']
                  config:
                    severity: warn
          - name: shared_match_flag
            data_type: CHARACTER VARYING(256)
            description: "Did the passenger share the vehicle with another passenger who booked separately at any point during the trip? (Y/N)"
            tests:
              - accepted_values:
                  values: ['Y', 'N']
                  config:
                    severity: warn
          - name: access_a_ride_flag
            data_type: CHARACTER VARYING(256)
            description: "Was the trip administered on behalf of the Metropolitan Transportation Authority (MTA)? (Y/N)"
            tests:
              - accepted_values:
                  values: ['Y', 'N']
                  config:
                    severity: warn
              - not_null
          - name: wav_request_flag
            data_type: CHARACTER VARYING(256)
            description: "Did the passenger request a wheelchair-accessible vehicle (WAV)? (Y/N)"
          - name: wav_match_flag
            data_type: CHARACTER VARYING(256)
            description: "Did the trip occur in a wheelchair-accessible vehicle (WAV)? (Y/N)"
            tests:
              - accepted_values:
                  values: ['Y', 'N']
                  config:
                    severity: warn
          - name: filename
            data_type: CHARACTER VARYING(256)

      - name: green_tripdata
        columns:
          - name: vendorid
            data_type: BIGINT
            description: "A code indicating the LPEP provider that provided the record.
                          1= Creative Mobile Technologies, LLC; 
                          2= VeriFone Inc."
          - name: lpep_pickup_datetime
            data_type: TIMESTAMP
            description: "The date and time when the meter was engaged. "
          - name: lpep_dropoff_datetime
            data_type: TIMESTAMP
            description: "The date and time when the meter was disengaged. "
          - name: store_and_fwd_flag
            data_type: CHARACTER VARYING(256)
            description: "This flag indicates whether the trip record was held in vehicle
                          memory before sending to the vendor, aka “store and forward,”
                          because the vehicle did not have a connection to the server.
                          Y= store and forward trip
                          N= not a store and forward trip"
          - name: ratecodeid
            data_type: DOUBLE
            description: "The final rate code in effect at the end of the trip.
                          1= Standard rate
                          2=JFK
                          3=Newark
                          4=Nassau or Westchester
                          5=Negotiated fare
                          6=Group ride"
          - name: pulocationid
            data_type: BIGINT
            description: "TLC Taxi Zone in which the taximeter was engaged"
          - name: dolocationid
            data_type: BIGINT
            description: "TLC Taxi Zone in which the taximeter was engaged"
          - name: passenger_count
            data_type: DOUBLE
            description: "The number of passengers in the vehicle.
                          This is a driver-entered value."
          - name: trip_distance
            data_type: DOUBLE
            description: "The elapsed trip distance in miles reported by the taximeter."
          - name: fare_amount
            data_type: DOUBLE
            description: "The time-and-distance fare calculated by the meter."
          - name: extra
            data_type: DOUBLE
            description: "Miscellaneous extras and surcharges. Currently, this only includes the $0.50 and $1 rush hour and overnight charges."
          - name: mta_tax
            data_type: DOUBLE
            description: "$0.50 MTA tax that is automatically triggered based on the metered rate in use."
          - name: tip_amount
            data_type: DOUBLE
            description: "Tip amount – This field is automatically populated for credit card tips. Cash tips are not included."
          - name: tolls_amount
            data_type: DOUBLE
            description: "Total amount of all tolls paid in trip. "
          - name: ehail_fee
            data_type: INTEGER
          - name: improvement_surcharge
            data_type: DOUBLE
            description: "$0.30 improvement surcharge assessed on hailed trips at the flag drop. The improvement surcharge began being levied in 2015."
          - name: total_amount
            data_type: DOUBLE
            description: "The total amount charged to passengers. Does not include cash tips."
          - name: payment_type
            data_type: DOUBLE
            description: "A numeric code signifying how the passenger paid for the trip.
                          1= Credit card
                          2= Cash
                          3= No charge
                          4= Dispute
                          5= Unknown
                          6= Voided trip"
          - name: trip_type
            data_type: DOUBLE
            description: "A code indicating whether the trip was a street-hail or a dispatch
                          that is automatically assigned based on the metered rate in use but
                          can be altered by the driver.
                          1= Street-hail
                          2= Dispatch"
          - name: congestion_surcharge
            data_type: DOUBLE
          - name: filename
            data_type: CHARACTER VARYING(256)

      - name: yellow_tripdata
        columns:
          - name: vendorid
            data_type: BIGINT
            description: "A code indicating the TPEP provider that provided the record.
                          1= Creative Mobile Technologies, LLC; 
                          2= VeriFone Inc."
          - name: tpep_pickup_datetime
            data_type: TIMESTAMP
            description: "The date and time when the meter was engaged"
          - name: tpep_dropoff_datetime
            data_type: TIMESTAMP
            description: "The date and time when the meter was disengaged. "
          - name: passenger_count
            data_type: DOUBLE
            description: "The number of passengers in the vehicle.
                          This is a driver-entered value."
          - name: trip_distance
            data_type: DOUBLE
            description: "The elapsed trip distance in miles reported by the taximeter."
          - name: ratecodeid
            data_type: DOUBLE
            description: "The final rate code in effect at the end of the trip.
                          1= Standard rate
                          2=JFK
                          3=Newark
                          4=Nassau or Westchester
                          5=Negotiated fare
                          6=Group ride"
          - name: store_and_fwd_flag
            data_type: CHARACTER VARYING(256)
            description: "This flag indicates whether the trip record was held in vehicle
                          memory before sending to the vendor, aka “store and forward,”
                          because the vehicle did not have a connection to the server.
                          Y= store and forward trip
                          N= not a store and forward trip"
          - name: pulocationid
            data_type: BIGINT
            description: "TLC Taxi Zone in which the taximeter was engaged"
          - name: dolocationid
            data_type: BIGINT
            description: "TLC Taxi Zone in which the taximeter was disengaged"
          - name: payment_type
            data_type: BIGINT
            description: "A numeric code signifying how the passenger paid for the trip.
                          1= Credit card
                          2= Cash
                          3= No charge
                          4= Dispute
                          5= Unknown
                          6= Voided trip"
          - name: fare_amount
            data_type: DOUBLE
            description: "The time-and-distance fare calculated by the meter."
          - name: extra
            data_type: DOUBLE
            description: "Miscellaneous extras and surcharges. Currently, this only includes
            the $0.50 and $1 rush hour and overnight charges"
          - name: mta_tax
            data_type: DOUBLE
            description: "$0.50 MTA tax that is automatically triggered based on the metered
            rate in use."
          - name: tip_amount
            data_type: DOUBLE
            description: "This field is automatically populated for credit card tips. Cash tips are not included."
          - name: tolls_amount
            data_type: DOUBLE
            description: "Total amount of all tolls paid in trip"
          - name: improvement_surcharge
            data_type: DOUBLE
            description: "$0.30 improvement surcharge assessed trips at the flag drop. 
                          The improvement surcharge began being levied in 2015."
          - name: total_amount
            data_type: DOUBLE
            description: "The total amount charged to passengers. Does not include cash tips."
          - name: congestion_surcharge
            data_type: DOUBLE
            description: "Total amount collected in trip for NYS congestion surcharge."
          - name: airport_fee
            data_type: DOUBLE
            description: "$1.25 for pick up only at LaGuardia and John F. Kennedy Airports"
          - name: filename
            data_type: CHARACTER VARYING(256)
