.once answers/average_time_between_pickups.txt
.read nyc_transit/target/compiled/nyc_transit/analyses/average_time_between_pickups.sql
.once answers/dedupe.txt
.read nyc_transit/target/compiled/nyc_transit/analyses/dedupe.sql
.once answers/pivot_trips_by_borough.txt
.read nyc_transit/target/compiled/nyc_transit/analyses/pivot_trips_by_borough.sql
.once answers/seven_day_moving_aggs_weather.txt
.read nyc_transit/target/compiled/nyc_transit/analyses/seven_day_moving_aggs_weather.sql
.once answers/seven_day_moving_average_prcp.txt
.read nyc_transit/target/compiled/nyc_transit/analyses/seven_day_moving_average_prcp.sql
.once answers/taxi_trips_no_valid_pickup_location_id.txt
.read nyc_transit/target/compiled/nyc_transit/analyses/taxi_trips_no_valid_pickup_location_id.sql
.once answers/trips_duration_grouped_by_borough_zone.txt
.read nyc_transit/target/compiled/nyc_transit/analyses/trips_duration_grouped_by_borough_zone.sql
.once answers/yellow_taxi_fare_comparison.txt
.read nyc_transit/target/compiled/nyc_transit/analyses/yellow_taxi_fare_comparison.sql
.once answers/zones_with_less_than_100k_trips.txt
.read nyc_transit/target/compiled/nyc_transit/analyses/zones_with_less_than_100k_trips.sql
.once answers/days_before_precip_more_bike_trips.txt
.read nyc_transit/target/compiled/nyc_transit/analyses/days_before_precip_more_bike_trips.sql
